# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      
      run: |
        touch .env
        echo MONGODB_CONNECTION_STR=${{ secrets.MONGODB_CONNECTION_STR }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        echo USER_EMAIL=${{ secrets.USER_EMAIL }} >> .env
        echo USER_PASSWORD=${{ secrets.USER_PASSWORD }} >> .env
        echo EMAIL_SENDINBLUE_ACCOUNT=${{ secrets.EMAIL_SENDINBLUE_ACCOUNT }} >> .env
        echo SENDINBLUE_SMTP_KEY=${{ secrets.SENDINBLUE_SMTP_KEY }} >> .env
        echo FRONTEND_URL=${{ secrets.FRONTEND_URL }} >> .env
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm i
    #- run: npm test
    - run: sudo systemctl reload supervisor