# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
      env:
        MONGODB_CONNECTION_STR = mongodb+srv://project_user:jdheyhrf73@cluster0.jgvs2.mongodb.net/proyectoFinal
        JWT_SECRET = verySecret
        USER_EMAIL = email@email.com
        USER_PASSWORD = 1234
        EMAIL_SENDINBLUE_ACCOUNT = email@email.com
        SENDINBLUE_SMTP_KEY = ******
    #- run: npm test
    - run: sudo systemctl reload supervisor
